language: ruby
rvm:
  - 2.3.3

script: 
  - bundle install
  - bundle exec jekyll build

after_success:
  - git clone https://github.com/mritd/mritd.me.git
  - cd mritd.me && rm -rf * && cp -r ../_site/* .
  - git config user.name "mritd"
  - git config user.email "mritd1234@gmail.com"
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --force https://$DEPLOY_TOKEN@github.com/mritd/mritd.me.git master
  - cd ../ && openssl enc -aes-256-ecb -salt -d -a -in cikey -out mritd.key -k $SSH_TOKEN && cat mritd.key
  - ssh -i mritd.key -q -o StrictHostKeyChecking=no root@mritd.me "docker restart mritd_jekyll_1"
  - rm -f mritd.key

branches:
    only:
    - master
env:
    global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
