# ---------------- #
#   Main Configs   #
# ---------------- #
title: Kopei
author: Kopei
subtitle: ""
description: ""
keywords: Kopei
url: "https://www.duduky.cn"
date_format: "ordinal"
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://github.com/Kopei/kopei.github.io
side_bar_repo_limit: 2

# ---------------- #
#      Author      #
# ---------------- #
organization: Secret
organization_url: https://github.com/Kopei/kopei.github.io
location: Shanghai, China
email: ncpbest@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基


  -
    href: /open-source/
    label: 开源

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
    - jekyll-sitemap
#    - jekyll-seo-tag
#    - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-feed
    - jemoji
#    - jekyll-mentions
    - jekyll-github-metadata
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: kopei
#douban_username: mritd
facebook_username: kopei
#weibo_username: mritd
#zhihu_username: mritd
twitter_username: kopei

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
disqus_username: www-duduky-cn-1
disqus_url: "https://www.duduky.cn"

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-114283725-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Python, Ruby, Docker, Kubernetes]
skill_mobile_app_keywords: [Python]
#skill_windows_keywords: []

# ---------------- #
# Github metadata  #
# ---------------- #
repository: Kopei/kopei.github.io
